# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jin Yong Yoo
nickname: Jeffrey
korean_name: 유진용
email: jy2ma@virginia.edu
description: >- # this means to ignore newlines until "baseurl:"
  I am a machine learning engineer at <a href="https://hyperconnect.com/en/">Hyperconnect</a>.
  Previously, I got my B.A. and M.S. from University of Virginia where I was advised by <a href="https://www.cs.virginia.edu/yanjun/">Yanjun Qi</a>.
research_interest:
  My current research interests are in open-domain conversation agents and natural language generation.
  While at UVA, I primarily worked on adversarial robustness of NLP models.
baseurl: "" # the subpath of your site, e.g. /blog
url: "jinyongyoo" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jinyongyoo
google_scholar_link: https://scholar.google.com/citations?user=qNoKYxYAAAAJ&hl=en 

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: node_modules

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
